add-auth-before calling delivery

diff --git a/.github/workflows/conan-library.yml b/.github/workflows/conan-library.yml
--- a/.github/workflows/conan-library.yml
+++ b/.github/workflows/conan-library.yml
@@ -223,6 +223,26 @@ jobs:
         with:
           name: conan-context
           path: .conan-context
+
+      - name: Extract authentication token
+        run: |
+          context=$(yq e '.bundle' "${CONAN_CONTEXT_PATH}")
+          owner=$(echo "${context}" | cut -d'/' -f1)
+          OWNER_GIT_TOKEN_SECRET=GIT_TOKEN_$(echo "${OWNER}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
+          # shellcheck disable=SC2086
+          all_secrets='${{ tojson(secrets) }}'
+          OWNER_GIT_TOKEN=$(echo "$all_secrets" | jq -r ".${OWNER_GIT_TOKEN_SECRET}")
+          all_secrets=''
+          if [ -z "${OWNER_GIT_TOKEN}" ] || [ "null" = "${OWNER_GIT_TOKEN}" ]; then
+            echo "Secret ${OWNER_GIT_TOKEN_SECRET} not found !"
+            echo "Please add secret ${OWNER_GIT_TOKEN_SECRET} to https://github.com/organizations/${GITHUB_REPOSITORY_OWNER}/settings/secrets/actions"
+            exit 1
+          else
+            echo "Found secret ${OWNER_GIT_TOKEN_SECRET} that will be use to trigger delivery of ${context}"
+          fi
+          echo "${OWNER_GIT_TOKEN}" > mytoken.txt
+          gh auth login --with-token < mytoken.txt
+          rm mytoken.txt
       - name: Call context delivery  
         run: |  
           context=$(yq e '.bundle' "${CONAN_CONTEXT_PATH}")
