fix remove clone.yml hopefully

diff --git a/.github/workflows/conan-context-delivery.yml b/.github/workflows/conan-context-delivery.yml
--- a/.github/workflows/conan-context-delivery.yml
+++ b/.github/workflows/conan-context-delivery.yml
@@ -157,7 +157,7 @@ jobs:
             echo "Will use upload repository url: ${upload_repository_url}"
             echo "Will use from repository url: ${from_repository_url}"
           fi     
-          echo "from_repository_url=$from_repository_url" >> "$GITHUB_OUTPUT"   
+          echo "from_repository_url=$from_repository_url" >> "$GITHUB_OUTPUT"
 
   apt-preparation:
     runs-on: ubuntu-latest
@@ -442,59 +442,66 @@ jobs:
           name: packages-delivery-${{ matrix.profile }}
           path: ./to_apt/packages.json
   
+  finalize-cloning:
+    runs-on: ubuntu-latest
+    needs:
+      - preflight-checks
+      - extract-collectors        
+      - clone-collector-workspace
+    if: needs.extract-collectors.outputs.from_repository_url != needs.extract-collectors.outputs.release_repo_url
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+
       - name: remove clone request if any
         id: finalize
         run: |
-          if [ -f clone.yml ]; then
-            echo "cloning=true" >> "${GITHUB_ENV}"   
-            echo "Clone successfully done, removing clone request"
-            DELIVERY_NAME=${{ needs.preflight-checks.outputs.delivery-name }}
+              echo "Clone successfully done, removing clone request"
+              DELIVERY_NAME=${{ needs.preflight-checks.outputs.delivery-name }}
 
-            : # Authenticate on current git repos
-            OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1) 
-            echo "owner ${OWNER}"
-            OWNER_GIT_TOKEN_SECRET=GIT_TOKEN_RELEASE_$(echo "${OWNER}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
-            # shellcheck disable=SC2086
-            all_secrets='${{ tojson(secrets) }}'
-            OWNER_GIT_TOKEN=$(echo "$all_secrets" | jq -r ".${OWNER_GIT_TOKEN_SECRET}")
-            all_secrets=''          
-            if [ -z "${OWNER_GIT_TOKEN}" ] || [ "null" = "${OWNER_GIT_TOKEN}" ]; then
-              echo "Secret ${OWNER_GIT_TOKEN_SECRET} not found !"
-              echo "Please add secret ${OWNER_GIT_TOKEN_SECRET} to https://github.com/organizations/${GITHUB_REPOSITORY}/settings/secrets/actions"
-              exit 1
-            else
-              echo "Found secret ${OWNER_GIT_TOKEN_SECRET}"
-            fi
-            echo "${OWNER_GIT_TOKEN}" > mytoken.txt
-            gh auth login --with-token < mytoken.txt
-            rm mytoken.txt
+              : # Authenticate on current git repos
+              OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1) 
+              echo "owner ${OWNER}"
+              OWNER_GIT_TOKEN_SECRET=GIT_TOKEN_RELEASE_$(echo "${OWNER}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
+              # shellcheck disable=SC2086
+              all_secrets='${{ tojson(secrets) }}'
+              OWNER_GIT_TOKEN=$(echo "$all_secrets" | jq -r ".${OWNER_GIT_TOKEN_SECRET}")
+              all_secrets=''          
+              if [ -z "${OWNER_GIT_TOKEN}" ] || [ "null" = "${OWNER_GIT_TOKEN}" ]; then
+                echo "Secret ${OWNER_GIT_TOKEN_SECRET} not found !"
+                echo "Please add secret ${OWNER_GIT_TOKEN_SECRET} to https://github.com/organizations/${GITHUB_REPOSITORY}/settings/secrets/actions"
+                exit 1
+              else
+                echo "Found secret ${OWNER_GIT_TOKEN_SECRET}"
+              fi
+              echo "${OWNER_GIT_TOKEN}" > mytoken.txt
+              gh auth login --with-token < mytoken.txt
+              rm mytoken.txt
 
-            : # get current sha of the file
-            URL="/repos/${GITHUB_REPOSITORY}/contents/clone.yml"
-            REF="release/${DELIVERY_NAME}"
-            echo "command gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' ${URL}?ref=refs/heads/${REF}"
-            sha=$(gh api -H 'Accept: application/vnd.github+json' \
-                -H 'X-GitHub-Api-Version: 2022-11-28' \
-                "${URL}?ref=refs/heads/${REF}" | jq -r '.sha')            
-            echo "sha ${sha}"
-            echo "command gh api --method DELETE -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' ${URL} -f  'message=clone finished' -f \"sha=${sha}\" -f \"branch=${REF}\""
+              : # get current sha of the file
+              URL="/repos/${GITHUB_REPOSITORY}/contents/clone.yml"
+              REF="release/${DELIVERY_NAME}"
+              echo "command gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' ${URL}?ref=refs/heads/${REF}"
+              sha=$(gh api -H 'Accept: application/vnd.github+json' \
+                  -H 'X-GitHub-Api-Version: 2022-11-28' \
+                  "${URL}?ref=refs/heads/${REF}" | jq -r '.sha')            
+              echo "sha ${sha}"
+              echo "command gh api --method DELETE -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' ${URL} -f  'message=clone finished' -f \"sha=${sha}\" -f \"branch=${REF}\""
 
-            : # delete the requets
-            gh api --method DELETE -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              "${URL}" \
-              -f "message=clone finished removing request ${GITHUB_RUN} : ${GITHUB_SERVER}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
-              -f "sha=${sha}" \
-              -f "branch=${REF}"
+              : # delete the requets
+              gh api --method DELETE -H "Accept: application/vnd.github+json" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                "${URL}" \
+                -f "message=clone finished removing request ${GITHUB_RUN} : ${GITHUB_SERVER}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
+                -f "sha=${sha}" \
+                -f "branch=${REF}"
 
-             : # byremoving clone.yml, this will trigger again this same workflow this time without the clone (hopefully)  
-          else
-             echo "cloning=false" >> "${GITHUB_ENV}"   
-          fi
+              : # byremoving clone.yml, this will trigger again this same workflow this time without the clone (hopefully)  
 
   dispatch-rebuild:
     runs-on: ubuntu-latest
-    if:  inputs.dispath-to-collectors && !needs.clone-collector-workspace.outputs.cloning 
+    if:  inputs.dispath-to-collectors && needs.extract-collectors.outputs.release_repo_url == needs.extract-collectors.outputs.from_repository_url
     needs:
       - extract-collectors
       - clone-collector-workspace
