fix: stop on conan create fail

diff --git a/.github/workflows/conan-library.yml b/.github/workflows/conan-library.yml
--- a/.github/workflows/conan-library.yml
+++ b/.github/workflows/conan-library.yml
@@ -209,7 +209,12 @@ jobs:
               build="${prev#*+}"
               build="${build%.*}"
               echo "Ripple building ${name} from version ${version} build ${build} ...."
-              cd "${name}" && git reset --hard "$sha" && PREVIOUS_VERSION="${version}+${build}" conan create . -pr:h "${{ matrix.profile }}" 2>&1 | tee conan_create.log && cd ..
+              cd "${name}"
+              git reset --hard "$sha"
+              # Following command must exit if conan create fail because we've set on top of this script 'set -o pipefail'
+              # Please do not add any command behind '| tee conan_create.log' that could change the return code
+              PREVIOUS_VERSION="${version}+${build}" conan create . -pr:h "${{ matrix.profile }}" 2>&1 | tee conan_create.log
+              cd ..
               if [ ${{ github.event_name }} != 'pull_request' ]; then
                 conan upload -r "${upload}" "${name}" --confirm
               fi  
